server:
  port: 7777 #配置端口号，默认是8080
  servlet:
    context-path: /husoul #项目根路径
#  tomcat:
#    uri-encoding: UTF-8
spring:
#  http:
#    encoding: #配置编码
#      enabled: true
#      charset: UTF-8
#      force: true
  profiles:
    active:
#      - pro #使用配置文件application-prod.yml
      - dev #使用配置文件application-dev.yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: top.oldmoon.husoul.model

#logging:
  #path: ./logs/file-server.log #配置日志保存路径，默认日志用的是logback，也可以改成log4j

audience:
  serverId: husoul
  publicKey: i0Qb7WSDBTeFNPl9yBoVFg==
  dueTime: 3600000 # 60分钟

dbinit:
  mysql:
    url: jdbc:mysql://127.0.0.1:3307/husoul?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    className: com.mysql.cj.jdbc.Driver

