spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://119.45.199.151:3306/blog?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull # JDBC url of the database.
    #    url: jdbc:mysql://119.45.199.151:3306/booking?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #    username: dev
    #    password: Dev@1997
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/husoul?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      min-idle: 5               #数据库连接池的最小维持连接数
      initial-size: 5           #初始化连接数
      max-total: 50            #最大连接数
      max-wait-millis: 200      #等待连接获取的最大超时时间
      validationQuery: SELECT 1 FROM soul
    # 初始化，最小，最大连接数
      initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 6000

file:
  default_path: F:\husoul

dbInit:
  dbs:
    dataSource: true