spring:
  datasource:
    name: datasource # Name of the datasource.
    #url: jdbc:mysql://119.45.199.151:3306/blog?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull # JDBC url of the database.
    #    url: jdbc:mysql://119.45.199.151:3306/booking?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #    username: dev
    #    password: Dev@1997
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/husoul?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    validationQuery: SELECT 1 FROM soul
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.7.120:1521:ORCL
#    username: CJBGD2021
#    password: hlkj
#    validationQuery: SELECT 1 FROM dual
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      query-timeout: 1
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 6000

file:
  default_path: /usr/local/jar/husoul/file/